### PR TITLE
Login & Registration refactored into single screen

### PR DESCRIPTION
**Pull request by Baluds**
code refactoring

Widget created for login and registration

### CODE REVIEW

**Comment by Baluds** [comment]
@ghpranav textfields can be disposed when we use TextEditingController, i have not yet created it and assigned to textfield that comes in backend part

**Comment by ghpranav** [comment]
If possible I would suggest you to use TextEditingController itself & add validators to input fields, which is better to be handled in frontend rather than backend.

**Comment by Baluds** [comment]
> If possible I would suggest you to use TextEditingController itself & add validators to input fields, which is better to be handled in front end rather than back end.

I have mentioned the positions for the error texts which will be displayed during text validation, there are other validations from database which should be included as well so i will make a commit when i am making the UI ready for suitable back end if that is okay with you, ill also add on TextEditingController then

**Comment by ghpranav** [comment]
> > If possible I would suggest you to use TextEditingController itself & add validators to input fields, which is better to be handled in front end rather than back end.
> 
> I have mentioned the positions for the error texts which will be displayed during text validation, there are other validations from database which should be included as well so i will make a commit when i am making the UI ready for suitable back end if that is okay with you, ill also add on TextEditingController then

At least add email address & password length validator now, we can think about other later once we integrate with backend. For instance, you can use following regex for email id validation:
`
^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,253}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,253}[a-zA-Z0-9])?)*$
`

**Comment by Baluds** [comment]
Text Validators added and TextEditingController dispose on screen change added

**Pull request merged**
